name: CI-CD

on:
  push:
    branches:
      - "master"

jobs:
  build-test-deploy:
    name: Build, test, deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"

      - uses: actions/checkout@v2

      - name: "Install dependencies"
        run: npm ci

      - name: "Build"
        run: npm run ci:build

      - name: "Test"
        run: npm run ci:test

      - name: "Deploy"
        run: |
          npm -g install firebase-tools
          firebase --token ${{ secrets.FIREBASE_TOKEN }} deploy --only hosting --project charts-poc
